// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w9z9xr91BzfJBdGd9K1NM4
// Component: ObvQXRNt7V
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants } from "../blank_project_mobile_first/PlasmicGlobalVariant__Screen"; // plasmic-import: 6KPrwB1vc_/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project_mobile_first/plasmic_blank_project_mobile_first.module.css"; // plasmic-import: w9z9xr91BzfJBdGd9K1NM4/projectcss
import * as sty from "./PlasmicManifest.module.css"; // plasmic-import: ObvQXRNt7V/css

import Ellipse2Icon from "../prytulak/icons/PlasmicIcon__Ellipse2"; // plasmic-import: o2LFLcguMd/icon
import group7520OmY6YnUp from "../prytulak/images/group75.svg"; // plasmic-import: 20omY6YNUp/picture

export type PlasmicManifest__VariantMembers = {};

export type PlasmicManifest__VariantsArgs = {};
type VariantPropType = keyof PlasmicManifest__VariantsArgs;
export const PlasmicManifest__VariantProps = new Array<VariantPropType>();

export type PlasmicManifest__ArgsType = {};
type ArgPropType = keyof PlasmicManifest__ArgsType;
export const PlasmicManifest__ArgProps = new Array<ArgPropType>();

export type PlasmicManifest__OverridesType = {
  root?: p.Flex<"div">;
  frame10?: p.Flex<"div">;
  frame9?: p.Flex<"div">;
  imageimage6?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  maskGroup?: p.Flex<"div">;
  img?: p.Flex<"img">;
  frame11?: p.Flex<"div">;
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў?: p.Flex<"div">;
};

export interface DefaultManifestProps {
  className?: string;
}

function PlasmicManifest__RenderFunc(props: {
  variants: PlasmicManifest__VariantsArgs;
  args: PlasmicManifest__ArgsType;
  overrides: PlasmicManifest__OverridesType;
  dataFetches?: PlasmicManifest__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"frame10"}
            data-plasmic-override={overrides.frame10}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame10)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame9"}
              data-plasmic-override={overrides.frame9}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame9)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mvwSc
                )}
              >
                {"Прытулак"}
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"imageimage6"}
              data-plasmic-override={overrides.imageimage6}
              className={classNames(defaultcss.all, sty.imageimage6)}
            >
              {true ? (
                <Ellipse2Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(defaultcss.all, sty.svg)}
                  role={"img"}
                />
              ) : null}

              <div
                data-plasmic-name={"maskGroup"}
                data-plasmic-override={overrides.maskGroup}
                className={classNames(defaultcss.all, sty.maskGroup)}
              >
                <img
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(defaultcss.img, sty.img)}
                  role={"img"}
                  src={group7520OmY6YnUp}
                />
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__q2Ufm
              )}
            >
              {"Манифест"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame11"}
              data-plasmic-override={overrides.frame11}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame11)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__zuXyx
                )}
              >
                {hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "Наш маніфэст:"
                  : "Наш маніфэст:"}
              </div>

              <div
                data-plasmic-name={
                  "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
                }
                data-plasmic-override={
                  overrides.прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў
                }
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.прытулакгэтапраеднасцьмынесуддзіміншыхлюдзейзатоештоянызрабіліцінемыпростанамагаемсярабіцьсваюсправудобрапрытулакгэтадапамогабеларусамукіевеякіяпапаліпаджорнавысістэмыівымушаныбылінепасваейволіпакідацьрадзімупрытулакгэтанепростадапамогагэтажаданнепадзяліццалюбоўюдацьчалавекуразуменнеіадчуваннетагоштовырашэннеягоныхпраблемгэтаячшэаднаперамогаабноўленнайбеларусіпадзяліццалюбоўюіпадтрымацьсуайчыннікаўцяжкімдляягостановішчыпрытулакгэтатакаяжлюбоўдасваіхваланцераўілюдзейякіяахвяруюцьсвойчаснаблагадзейнасцькабянымагліспакойназаймаццасваейсправайнедумаючыпратоеякзарабіцьнажыццеупрытулкупрымагчымасцімыхочамдаведваццабольшпраадзінаднагодзяліццавопытамарганізовацьcумесныямерапрыемствыіпростагубляцьчасўаттачэнніблізкіхсяброў
                )}
              >
                {hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "Прытулак, гэта пра еднасць: мы не суддзім іншых людзей за тое што яны зрабілі ці не, мы проста намагаемся рабіць сваю справу добра\n\nПрытулак - гэта дапамога беларусам у Кіеве, якія папалі пад жорнавы сістэмы і вымушаны былі не па сваей волі пакідаць Радзіму\n\nПрытулак - гэта не проста дапамога, гэта жаданне падзяліцца любоўю. Даць чалавеку разуменне і адчуванне таго, што вырашэнне ягоных праблем, гэта ячшэ адна перамога Абноўленнай Беларусі, падзяліцца любоўю і падтрымаць суайчынніка ў цяжкім для яго становішчы.\n\nПрытулак - гэта такая ж любоў да сваіх валанцераў і людзей якія ахвяруюць свой час на благадзейнасць! Каб яны маглі спакойна займацца сваей справай не думаючы пра тое як зарабіць на жыцце!\n\nУ прытулку пры магчымасці мы хочам даведвацца больш пра адзін аднаго, дзяліцца вопытам, арганізоваць cумесныя мерапрыемствы і проста губляць час ў аттачэнні блізкіх сяброў\n\n\n"
                  : "Прытулак, гэта пра еднасць: мы не суддзім іншых людзей за тое што яны зрабілі ці не, мы проста намагаемся рабіць сваю справу добра\n\nПрытулак - гэта дапамога беларусам у Кіеве, якія папалі пад жорнавы сістэмы і вымушаны былі не па сваей волі пакідаць Радзіму\n\nПрытулак - гэта не проста дапамога, гэта жаданне падзяліцца любоўю. Даць чалавеку разуменне і адчуванне таго, што вырашэнне ягоных праблем, гэта ячшэ адна перамога Абноўленнай Беларусі, падзяліцца любоўю і падтрымаць суайчынніка ў цяжкім для яго становішчы.\n\nПрытулак - гэта такая ж любоў да сваіх валанцераў і людзей якія ахвяруюць свой час на благадзейнасць! Каб яны маглі спакойна займацца сваей справай не думаючы пра тое як зарабіць на жыцце!\n\nУ прытулку пры магчымасці мы хочам даведвацца больш пра адзін аднаго, дзяліцца вопытам, арганізоваць cумесныя мерапрыемствы і проста губляць час ў аттачэнні блізкіх сяброў\n\n\n"}
              </div>
            </p.Stack>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "frame10",
    "frame9",
    "imageimage6",
    "svg",
    "maskGroup",
    "img",
    "frame11",
    "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
  ],
  frame10: [
    "frame10",
    "frame9",
    "imageimage6",
    "svg",
    "maskGroup",
    "img",
    "frame11",
    "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
  ],
  frame9: ["frame9"],
  imageimage6: ["imageimage6", "svg", "maskGroup", "img"],
  svg: ["svg"],
  maskGroup: ["maskGroup", "img"],
  img: ["img"],
  frame11: [
    "frame11",
    "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
  ],
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў:
    [
      "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
    ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  frame10: "div";
  frame9: "div";
  imageimage6: "div";
  svg: "svg";
  maskGroup: "div";
  img: "img";
  frame11: "div";
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicManifest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicManifest__VariantsArgs;
    args?: PlasmicManifest__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicManifest__Fetches;
  } & Omit<PlasmicManifest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicManifest__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicManifest__ArgProps,
      internalVariantPropNames: PlasmicManifest__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicManifest__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicManifest";
  } else {
    func.displayName = `PlasmicManifest.${nodeName}`;
  }
  return func;
}

export const PlasmicManifest = Object.assign(
  // Top-level PlasmicManifest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame10: makeNodeComponent("frame10"),
    frame9: makeNodeComponent("frame9"),
    imageimage6: makeNodeComponent("imageimage6"),
    svg: makeNodeComponent("svg"),
    maskGroup: makeNodeComponent("maskGroup"),
    img: makeNodeComponent("img"),
    frame11: makeNodeComponent("frame11"),
    прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў:
      makeNodeComponent(
        "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
      ),

    // Metadata about props expected for PlasmicManifest
    internalVariantProps: PlasmicManifest__VariantProps,
    internalArgProps: PlasmicManifest__ArgProps
  }
);

export default PlasmicManifest;
/* prettier-ignore-end */
