// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w9z9xr91BzfJBdGd9K1NM4
// Component: ur16OaAaQB
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: xidBG5GAId/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: w9z9xr91BzfJBdGd9K1NM4/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: ur16OaAaQB/css

import prytulakLogoLxzuuNiCf from "./images/prytulakLogo.svg"; // plasmic-import: lxzuuNI-cf/picture

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  frame10?: p.Flex<"div">;
  frame9?: p.Flex<"div">;
  img?: p.Flex<"img">;
  frame11?: p.Flex<"div">;
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"frame10"}
            data-plasmic-override={overrides.frame10}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame10)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame9"}
              data-plasmic-override={overrides.frame9}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame9)}
            >
              <img
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(defaultcss.img, sty.img)}
                role={"img"}
                src={prytulakLogoLxzuuNiCf}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__jUcAd
                )}
              >
                {"Прытулак"}
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__sz4Ev
              )}
            >
              {"Жылле для уцякачоў з Беларусі ў Кіеве"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__ezlIw)}
            >
              <Button
                className={classNames("__wab_instance", sty.button__ayseC)}
                label={"Хочу помочь"}
                to={"https://forms.gle/MDj5nWeNGkpkyWrc8" as const}
              />

              <Button
                className={classNames("__wab_instance", sty.button__yv8V7)}
                label={"Мне нужна помощь"}
              />

              <Button
                className={classNames("__wab_instance", sty.button__otn6H)}
                label={"Хочу стать волонтером"}
              />
            </p.Stack>
          </p.Stack>

          <div className={classNames(defaultcss.all, sty.freeBox__jCW)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame11"}
              data-plasmic-override={overrides.frame11}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame11)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__t3IZ
                )}
              >
                {"Наш маніфэст:"}
              </div>

              <div
                data-plasmic-name={
                  "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
                }
                data-plasmic-override={
                  overrides.прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў
                }
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.прытулакгэтапраеднасцьмынесуддзіміншыхлюдзейзатоештоянызрабіліцінемыпростанамагаемсярабіцьсваюсправудобрапрытулакгэтадапамогабеларусамукіевеякіяпапаліпаджорнавысістэмыівымушаныбылінепасваейволіпакідацьрадзімупрытулакгэтанепростадапамогагэтажаданнепадзяліццалюбоўюдацьчалавекуразуменнеіадчуваннетагоштовырашэннеягоныхпраблемгэтаячшэаднаперамогаабноўленнайбеларусіпадзяліццалюбоўюіпадтрымацьсуайчыннікаўцяжкімдляягостановішчыпрытулакгэтатакаяжлюбоўдасваіхваланцераўілюдзейякіяахвяруюцьсвойчаснаблагадзейнасцькабянымагліспакойназаймаццасваейсправайнедумаючыпратоеякзарабіцьнажыццеупрытулкупрымагчымасцімыхочамдаведваццабольшпраадзінаднагодзяліццавопытамарганізовацьcумесныямерапрыемствыіпростагубляцьчасўаттачэнніблізкіхсяброў
                )}
              >
                {
                  "Прытулак, гэта пра еднасць: мы не суддзім іншых людзей за тое што яны зрабілі ці не, мы проста намагаемся рабіць сваю справу добра\n\nПрытулак - гэта дапамога беларусам у Кіеве, якія папалі пад жорнавы сістэмы і вымушаны былі не па сваей волі пакідаць Радзіму\n\nПрытулак - гэта не проста дапамога, гэта жаданне падзяліцца любоўю. Даць чалавеку разуменне і адчуванне таго, што вырашэнне ягоных праблем, гэта ячшэ адна перамога Абноўленнай Беларусі, падзяліцца любоўю і падтрымаць суайчынніка ў цяжкім для яго становішчы.\n\nПрытулак - гэта такая ж любоў да сваіх валанцераў і людзей якія ахвяруюць свой час на благадзейнасць! Каб яны маглі спакойна займацца сваей справай не думаючы пра тое як зарабіць на жыцце!\n\nУ прытулку пры магчымасці мы хочам даведвацца больш пра адзін аднаго, дзяліцца вопытам, арганізоваць cумесныя мерапрыемствы і проста губляць час ў аттачэнні блізкіх сяброў\n\n\n"
                }
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "frame10",
    "frame9",
    "img",
    "frame11",
    "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
  ],
  frame10: ["frame10", "frame9", "img"],
  frame9: ["frame9", "img"],
  img: ["img"],
  frame11: [
    "frame11",
    "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
  ],
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў:
    [
      "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
    ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  frame10: "div";
  frame9: "div";
  img: "img";
  frame11: "div";
  прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame10: makeNodeComponent("frame10"),
    frame9: makeNodeComponent("frame9"),
    img: makeNodeComponent("img"),
    frame11: makeNodeComponent("frame11"),
    прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў:
      makeNodeComponent(
        "прытулакГэтаПраЕднасцьМыНеСуддзімІншыхЛюдзейЗаТоеШтоЯныЗрабіліЦіНеМыПростаНамагаемсяРабіцьСваюСправуДобраПрытулакГэтаДапамогаБеларусамУКіевеЯкіяПапаліПадЖорнавыСістэмыІВымушаныБыліНеПаСваейВоліПакідацьРадзімуПрытулакГэтаНеПростаДапамогаГэтаЖаданнеПадзяліццаЛюбоўюДацьЧалавекуРазуменнеІАдчуваннеТагоШтоВырашэннеЯгоныхПраблемГэтаЯчшэАднаПерамогаАбноўленнайБеларусіПадзяліццаЛюбоўюІПадтрымацьСуайчыннікаЎЦяжкімДляЯгоСтановішчыПрытулакГэтаТакаяЖЛюбоўДаСваіхВаланцераўІЛюдзейЯкіяАхвяруюцьСвойЧасНаБлагадзейнасцьКабЯныМагліСпакойнаЗаймаццаСваейСправайНеДумаючыПраТоеЯкЗарабіцьНаЖыццеУПрытулкуПрыМагчымасціМыХочамДаведваццаБольшПраАдзінАднагоДзяліццаВопытамАрганізовацьCумесныяМерапрыемствыІПростаГубляцьЧасЎАттачэнніБлізкіхСяброў"
      ),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
