// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w9z9xr91BzfJBdGd9K1NM4
// Component: ObvQXRNt7V
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: w9z9xr91BzfJBdGd9K1NM4/projectcss
import * as sty from "./PlasmicManifest.module.css"; // plasmic-import: ObvQXRNt7V/css

export type PlasmicManifest__VariantMembers = {};

export type PlasmicManifest__VariantsArgs = {};
type VariantPropType = keyof PlasmicManifest__VariantsArgs;
export const PlasmicManifest__VariantProps = new Array<VariantPropType>();

export type PlasmicManifest__ArgsType = {};
type ArgPropType = keyof PlasmicManifest__ArgsType;
export const PlasmicManifest__ArgProps = new Array<ArgPropType>();

export type PlasmicManifest__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultManifestProps {
  className?: string;
}

function PlasmicManifest__RenderFunc(props: {
  variants: PlasmicManifest__VariantsArgs;
  args: PlasmicManifest__ArgsType;
  overrides: PlasmicManifest__OverridesType;
  dataFetches?: PlasmicManifest__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicManifest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicManifest__VariantsArgs;
    args?: PlasmicManifest__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicManifest__Fetches;
  } & Omit<PlasmicManifest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicManifest__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicManifest__ArgProps,
      internalVariantPropNames: PlasmicManifest__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicManifest__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicManifest";
  } else {
    func.displayName = `PlasmicManifest.${nodeName}`;
  }
  return func;
}

export const PlasmicManifest = Object.assign(
  // Top-level PlasmicManifest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicManifest
    internalVariantProps: PlasmicManifest__VariantProps,
    internalArgProps: PlasmicManifest__ArgProps
  }
);

export default PlasmicManifest;
/* prettier-ignore-end */
